language: java
jdk:
  - oraclejdk8
before_script:
  - git clone git@github.com:belakede/thesis-core.git /tmp/thesis-core
  - mvn install -Dmaven.test.skip=true -f /tmp/thesis-core/pom.xml
after_script:
  - rm -rf /tmp/thesis-core